# Generated by Django 5.2.4 on 2025-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('SITE', 'Site'), ('SUPPLIER', 'Supplier')], default='WAREHOUSE', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
